name: Setup Windows VM with Ngrok

on: [push]

jobs:
  setup-windows:
    runs-on: windows-latest  # This runs on a Windows GitHub Actions runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ngrok
      run: |
        $ngrokUrl = "https://bin.equinox.io/c/111111/ngrok-stable-windows-amd64.zip" # Old URL
        $latestNgrokUrl = "https://bin.equinox.io/c/111111/ngrok-stable-windows-amd64.zip"
        $ngrokDownloadPath = "$env:temp/ngrok.zip"

        # Download Ngrok
        Invoke-WebRequest -Uri $latestNgrokUrl -OutFile $ngrokDownloadPath

        # Unzip the Ngrok executable
        Expand-Archive -Path $ngrokDownloadPath -DestinationPath "$env:temp/ngrok"
        Remove-Item $ngrokDownloadPath

        # Move Ngrok to a usable location
        Move-Item -Path "$env:temp/ngrok/ngrok.exe" -Destination "$env:ProgramFiles/ngrok" -Force

    - name: Start Ngrok
      run: |
        Start-Process -NoNewWindow -FilePath "$env:ProgramFiles/ngrok/ngrok.exe" -ArgumentList "tcp 3389" # Expose RDP port (3389)

    - name: Display Ngrok Public URL
      run: |
        Start-Sleep -Seconds 10  # Wait for Ngrok to start
        curl http://localhost:4040/api/tunnels | ConvertFrom-Json | Select-Object -ExpandProperty tunnels | Select-Object -First 1 | Select-Object -ExpandProperty public_url
